#!/bin/bash
# shellcheck disable=SC1090,SC1091
err(){ echo "$*"; exit 1;}
prog=mailpixtracker
# These must be defined in the conf file
name=
dest=
url=
conf=()
if [[ -n "$1" ]]; then conf=("$1")
elif [[ -s .$prog.conf ]]; then conf=(".$prog.conf")
else err "Please make a .$prog.conf config file, see $prog-sample.conf"
fi
. "${conf[0]}"
name="${name//[^_[:alnum:]/}"
[[ -z "$name" ]] && err "Empty or invalid name"
(( ${#name} < 8)) && err "Admin nmae too short!"

for i in INSTALL $prog "${conf[@]}" *.conf; do
    [[ "${i:0:1}" == '*' ]] && continue
    grep -q '^#!/bin/bash' "$i" || continue
    if ! bash -n "$i"; then
        echo "************ $i: Syntax errors, No installation done" >&2
        exit 1
    fi
    scout=$(shellcheck "$i")
    if [[ -n "$scout" ]]; then
        echo "$scout"
        echo "************ $i: shellcheck warnings, No installation done" >&2
        exit 2
    fi
done

rsync -ai --out-format="%n" $prog "$dest/$name"
rsync -ai --out-format="%n" tracker "$dest/_"

echo "Installed at ${url:-YOUR-CGI-BIN-URL}/$name"

