#!/bin/bash
# VERSION 3.1.0
# source: 'https://github.com/ColasNahaboo/mailpixtracker'
################################# TRACKER: provide a 1x1 pixel, logs the access

nl=$'\n';  tab=$'\t'           # some useful constants
pixel=../data/p.png
# cache 1x1 transparent pixel PNG if needed
[[ -e "$pixel" ]] ||
    base64 -d <<<'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==' >"$pixel"

# Then log only if the url was for a valid and active tracker:
# mpturl/_/NN-nnpass or mpturl/_/~guestid/NN-nnpass
if [[ $PATH_INFO =~ (/[~][[:alnum:]]+)?/[[:digit:]]+-[[:alnum:]]+$ ]]; then
    meta=../data"$PATH_INFO".meta
    # log only if metafile exists: was properly created by the admin GUI
    if [[ -e "$meta" ]]; then
        date=$(date --iso=seconds -u)
        clienthost=$(host "$REMOTE_ADDR" | grep -oP 'domain name pointer +\K.*' | head -n 1)
        echo "$date${tab}$REMOTE_ADDR${tab}${clienthost%.}${tab}$HTTP_USER_AGENT" >>"${meta%.meta}".log
    fi
fi

# Always return the 1x pixel to avoid triggering a broken image on client
echo "Content-Type:image/png$nl"
cat "$pixel"
exit 0
