# Needs a2enmod headers rewrite ssl cgid
<VirtualHost *:443>
    ServerName my.mailpixtracker.org
    
    DocumentRoot /www/mpt/cgi

    # every top-level URL is a CGI script
    <Location />
        Require all granted
        AllowOverride None
        Options +ExecCGI -Indexes +FollowSymLinks
        SetHandler cgi-script
    </Location>

    # Important security measure since we use Capability URLs
    Header always set Referrer-Policy "no-referrer"

    RewriteEngine On
    # Admin IPs allowed to redirect (chain [OR] for multiple addresses)
    #RewriteCond %{REMOTE_ADDR} ^96\.40\.58\.240$ [OR]
    RewriteCond %{REMOTE_ADDR} ^30\.9\.145\.39$
    # Redirect / to our mpt admin id. Choose one with doc/random-string.sh
    RewriteRule ^(/)$ /gZu2SpMbpJ [R=301,L]

    ErrorLog ${APACHE_LOG_DIR}/mailpixtracker_error.log
    CustomLog ${APACHE_LOG_DIR}/mailpixtracker_access.log combined

    # Exception for /robots.txt
    Alias /robots.txt /www/mpt/robots.txt
    <Location /robots.txt>
        SetHandler none
        Options -ExecCGI
    </Location>

    # Redirect 404s for favicon since it is provided by the cgi script
    RewriteCond %{REQUEST_URI} ^/favicon.ico$
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ - [R=204,L]

    # SSL Certificates
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/apache.crt
    SSLCertificateKeyFile /etc/ssl/private/apache.key
</VirtualHost>
